### ISSUE TITLE
mapa mental 

### ISSUE THREAD

**Issue by lourdeshernandez2003** [SistemasTecTlaxiaco/mapa-mental-lourdeshernandez2003#3]
[MAPA MENTAL-MARIA DE LOURDES.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-lourdeshernandez2003/files/7334511/MAPA.MENTAL-MARIA.DE.LOURDES.pdf)

**Comment by Arlet04** [comment]
Contiene todos los elementos que se solicitan en la rubrica, define los conceptos claramente y tiene coherencia entre si.
Total: 100 puntos
Calificación:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
